### ISSUE TITLE
StopIteration exception thrown during GraphQLAnalysis

### ISSUE THREAD

**Issue by smc395** [Nuri22/csDetector#3]
Hello Nuri,

Thank you for making this tool publicly available. I have been trying to get the tool to work for class project, but encountering issues during the GraphQLAnalysis step. Specifically, I have been encountering a `StopIteration` exception at line 76 of `politenessAnalysis.py` when the parser is transforming the corpus. It seems to be something to do with ConvoKit. I followed the instructions at [https://convokit.cornell.edu/documentation/install.html](https://convokit.cornell.edu/documentation/install.html) and confirmed I have the correct ConvoKit version as specified in the `requirements.txt`. I have also followed the post-install steps on the ConvoKit website.
![image](https://user-images.githubusercontent.com/6887449/202922470-3abd1ece-169c-4230-8896-68e43657f771.png)

Here is part of the stack trace:
![image](https://user-images.githubusercontent.com/6887449/202922537-e79e99d4-2321-411f-b32f-a2a3f88febb8.png)

I believe I have installed all required dependencies via the `requirements.txt`. I used the GitHub repo [https://github.com/google/tangent](https://github.com/google/tangent) like in your demo video for the `-r` parameter. I am running on Windows 10 using Python 3.8.3.

Do you have any tips on how I could resolve this? Thank you for your time.

**Comment by Almarimi23** [comment]
> Hello Nuri,
> 
> Thank you for making this tool publicly available. I have been trying to get the tool to work for class project, but encountering issues during the GraphQLAnalysis step. Specifically, I have been encountering a `StopIteration` exception at line 76 of `politenessAnalysis.py` when the parser is transforming the corpus. It seems to be something to do with ConvoKit. I followed the instructions at https://convokit.cornell.edu/documentation/install.html and confirmed I have the correct ConvoKit version as specified in the `requirements.txt`. I have also followed the post-install steps on the ConvoKit website. ![image](https://user-images.githubusercontent.com/6887449/202922470-3abd1ece-169c-4230-8896-68e43657f771.png)
> 
> Here is part of the stack trace: ![image](https://user-images.githubusercontent.com/6887449/202922537-e79e99d4-2321-411f-b32f-a2a3f88febb8.png)
> 
> I believe I have installed all required dependencies via the `requirements.txt`. I used the GitHub repo https://github.com/google/tangent like in your demo video for the `-r` parameter. I am running on Windows 10 using Python 3.8.3.
> 
> Do you have any tips on how I could resolve this? Thank you for your time.

Thank you for using csDetector tool.

We recommended run the tool by the executable file way under windows to avoid such errors and for a quick and simple setup.

The error because the version v2.4.4 of convokit no longer being compatible with spaCy.

**Comment by Almarimi23** [comment]
The error because the version v2.4.4 of convokit no longer being compatible with spaCy.

We recommended run the tool by the executable file way under windows to avoid such errors and for a quick and simple setup.
